### ISSUE TITLE
Needed Meta Queries

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/MediaWiki-Butt-Ruby#6]
This is a list of needed meta queries, organized by module.
* [x] UserInfo
  * [x] `hasmsg`, returns true if ['query']['userinfo']['messages'] == "", else false
  * [x] `changeablegroups`, returns a hash of all the groups that the user can add/remove people from, formatted as `{ 'add' => [], 'remove' => [], 'addself' => [], 'removeself' => [] }`
  * [x] `options`, returns a hash containing all options and their values, basically identical to what the wiki provides.
  * [x] `realname`, returns a string containing their real name, or nil if it is ""
  * [x] `email`, returns a string containing their email address, or nil if it is ""

* [x] FileRepoInfo
  * [x] `name|displayname`, returns a hash of the names and their displaynames, example: `{ 'hydra-commons' => 'a shared repository', 'local' => nil }`
  * [x] `name|rootUrl`, returns a hash of the names and their rootUrls, example: `{ 'hydra-commons' => http://hydra-media.cursecdn.com/ftb.gamepedia.com', 'local' => 'http://hydra-media.cursecdn.com/ftb.gamepedia.com' }`
  * [x] `name|local`, returns a hash of the names and whether they are local or not, example: `{ 'hydra-commons' => false, 'local' => true }`
  * [x] `name|url`, returns a hash of the names and their URLs, example: `{ 'hydra-commons` => 'http://hydra-media.cursecdn.com/ftb.gamepedia.com', 'local' => 'http://hydra-media.cursecdn.com/ftb.gamepedia.com' }`
  * [x] `name|thumbUrl`, returns a hash of the names and their thumbnail URLs, example: `{ 'hydra-commons` => 'http://hydra-media.cursecdn.com/ftb.gamepedia.com/thumb', 'local' => 'http://hydra-media.cursecdn.com/ftb.gamepedia.com/thumb' }`
  * [x] `name|favicon`, returns a hash of the names and their favicon URLs, example: `{ `hydra-commons` => 'http://hydra-media.cursecdn.com/commons.cursetech.com/6/64/Favicon.ico', 'local' => 'http://hydra-media.cursecdn.com/ftb.gamepedia.com/6/64/Favicon.ico' }`

* [x] SiteInfo
  * [x] `namespaces`, returns a hash of the IDs and their names ('*'), example: `{ 'User talk' => 3 }`
  * [x] `namespacealiases`, returns a hash of the IDs and their names ('*'), like above.
  * [x] `specialpagealiases`, returns a hash of the realname and their aliases
  * [x] `magicwords`, returns an array of all magic word 'names'
  * [x] `usergroups`, returns a hash with arrays of all usergroups and their rights, example: `{ '*' => ['can shit into xbony's mouth'] }`
  * [x] `fileextensions`, returns an array of all file extensions allowed on the wiki. upload should be slightly updated to require a check in this array, so that it's more safe.
  * [x] `restrictions`, returns a hash basically identical to the one that the API provides.
  * [x] `skins`, returns an array of all the '*' values
  * [x] `extensiontags`, returns an array of all extension tags
  * [x] `functionhooks`, returns an array of all function hooks
  * [x] `variables`, returns an array of all variable IDs

@xbony2 I don't see allmessages being very useful. What do you think?
